package com.first.project.user_management_system.user;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

@Entity
@Table(name = "users", uniqueConstraints = {@UniqueConstraint(columnNames = "email")})
@Getter @Setter @AllArgsConstructor @NoArgsConstructor @ToString
public class User {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // Matches GENERATED BY DEFAULT AS IDENTITY
	@Column(name = "user_id")
	private long id;

	@Column(name = "first_name", nullable = false, length = 255)
	private String firstName;

	@Column(name = "last_name", nullable = false, length = 255)
	private String lastName;

	@Column(name = "birth_date")
	private LocalDate birthDate;

	@Column(name = "mobile", nullable = true)
	private String mobile;

	@Column(name = "email", nullable = false, length = 255)
	private String email;

	@Column(name = "username", nullable = false, length = 255)
	private String username;

	@Column(name = "password", nullable = false, length = 255)
	private String password;

	@Column(name = "role", nullable = false,length = 255)
	private String role;

	@Column(name= "country", nullable = false,length = 255)
	private  String country;
}
